export default [ 
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Ch1.jpg',
    title: "Penguin Punk #27",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 1,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Ch2.jpg',
    title: "Penguin Punk #26",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 2,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Ch3.jpg',
    title: "Penguin Punk #25",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 3,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Ch4.jpg',
    title: "Penguin Punk #24",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 4,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Ch5.jpg',
    title: "Penguin Punk #23",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 5,
  },


  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/1.jpg',
    title: "Hamburg Penguin #20",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 6,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/2.jpg',
    title: "Hot Dog Penguin #19",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 7,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/3.jpg',
    title: "Milkshake Penguin #18",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 8,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/4.jpg',
    title: "Chinese Food Penguin #17",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 9,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/5.jpg',
    title: "Sushi Penguin #16",
    number: "",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 10,
  },

  
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/1.gif',
    title: "CJAI NFT Collectibles",
    number: "No. 0605",
    desc: 'TSA NFT Studio',
    link: '/nft/products/category/5',
    mediaType: 1,
    id: 11,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/haha.gif',
    title: "TSANFT",
    number: "No.73",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 12,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Rhythm.gif',
    title: "TSANFT",
    number: "No.74",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/1',
    mediaType: 1,
    id: 13,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_09.gif',
    title: "Heaven and Earth No. 9",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 14,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_11.gif',
    title: "Heaven and Earth No. 11",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 15
  },

]