export default [ 
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/1.gif',
    title: "CJAI NFT Collectibles",
    number: "No. 0605",
    desc: 'TSA NFT Studio',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 1,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/2.png',
    title: "CaoJunNFT Collectibles",
    number: "No. 0605",
    desc: 'Once in a Millennium',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 2,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/3.mp4',
    title: "CaoJunNFT Collectibles",
    number: "",
    desc: 'No.0565,8306,7615,9131',
    link: 'https://www.icashrewards.io/tsanft',
    mediaType: 2,
    id: 3,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/4.gif',
    title: "CJAI NFT Collectibles",
    number: "No.9134",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 4,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/beginning.png',
    title: "TSANFT",
    number: "No.75",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/4',
    mediaType: 1,
    id: 5,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/haha.gif',
    title: "TSANFT",
    number: "No.73",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/4',
    mediaType: 1,
    id: 6,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/Rhythm.gif',
    title: "TSANFT",
    number: "No.74",
    desc: '',
    link: 'https://www.teaswap.art/nft/products/category/4',
    mediaType: 1,
    id: 7
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_01.gif',
    title: "Heaven and Earth No. 1",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 8
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_05.gif',
    title: "Heaven and Earth No. 5",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 9
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_09.gif',
    title: "Heaven and Earth No. 9",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 10
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/HeavenAndEarth_11.gif',
    title: "Heaven and Earth No. 11",
    number: "",
    desc: ``,
    link: 'https://www.teaswap.live/hotbids-digitalnft',
    mediaType: 1,
    id: 11
  },

]