export default [ 
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/1.gif',
    title: "CJA NFT Collectibles",
    number: "No. 0605",
    desc: 'TSA NFT Studio',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 1,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/2.png',
    title: "CaoJunNFT Collectibles",
    number: "No. 0605",
    desc: 'Once in a Millennium',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 2,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/3.mp4',
    title: "CaoJunNFT Collectibles",
    number: "",
    desc: 'No.0565,8306,7615,9131',
    link: '/nft/products/category/1',
    mediaType: 2,
    id: 3,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/4.gif',
    title: "CJAI NFT Collectibles",
    number: "No.9134",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 4,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/5.png',
    title: "CaoJunNFT Collectibles",
    number: "No.9134",
    desc: 'Once in a Millennium',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 5,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/6.gif',
    title: "CJAI Collectibles",
    number: "No.7611",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 6,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/7.png',
    title: "CJAI Collectibles",
    number: "No.7611",
    desc: `pring's News`,
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 7
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/8.png',
    title: "CaoJunNFT Collectibles",
    number: "No.8304",
    desc: `Purple Pavilion and Cyan Cloud`,
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 8
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/9.gif',
    title: "CJAI Collectibles",
    number: "Gold Grass No.8304",
    desc: ``,
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 9
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/10.gif',
    title: "CJAI Collectibles",
    number: "Gateway to Nature No.0602",
    desc: ``,
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 10
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro1/11.gif',
    title: "CJAI Collectibles",
    number: "Fishing Lake No.7611",
    desc: ``,
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 11
  },
]