export default [ 
  // {
  //   picture_url: process.env.PUBLIC_URL + '/nft/pro2/1.gif',
  //   title: "TSA Broadway Collectors Club",
  //   number: "No.100",
  //   desc: 'TSA NFT Studio',
  //   link: '/nft/products/category/1',
  //   mediaType: 1,
  //   id: 1,
  // },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/2.gif',
    title: "TSANFT No. 7 Broadway River",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 2,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/3.gif',
    title: "TSANFT No.4 Doge Shop",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 3,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/4.gif',
    title: "TSANFT No.5 CJAI",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 4,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/5.gif',
    title: "TSANFT No.3 BiKi Shop",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 5,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/6.gif',
    title: "TSANFT No.1 Voyage to Metaverse",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 6,
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/7.gif',
    title: "TSANFT No.2 Voyage to Metaverse",
    number: "",
    desc: '',
    link: '/nft/products/category/1',
    mediaType: 1,
    id: 7
  },
  {
    picture_url: process.env.PUBLIC_URL + '/nft/pro2/8.gif',
    title: "TSANFT No.6 BNB Shop",
    number: "",
    desc: '',
    link: '/nft/products/304',
    mediaType: 1,
    id: 8
  }
]